--1
SELECT  RUTEMP,
        SUBSTR(RUTEMP,1,LENGTH(RUTEMP)-1) || '-' || SUBSTR(RUTEMP,-1) AS "RUN EMPLEADO",
        UPPER(PATERNO || ' ' || MATERNO || ' ' || NOMBRE) AS "NOMBRE",
        DIRECCION,
        FONO1,
        NVL(FONO2, 'NO TIENE FONO') AS "FONO2"
FROM EMPLEADO
ORDER BY PATERNO;

--2
SELECT  SUBSTR(RUTEMP, 1, LENGTH(RUTEMP)-1) || '-' || SUBSTR(RUTEMP,-1) RUT_EMPLEADO,
        SUELDO,
        LPAD(TRUNC(SUELDO/100000) || '%', 15, ' ') AS PORCENTAJE
FROM EMPLEADO
WHERE IDCATEGORIA = 2;

--3
SELECT  INITCAP(PATERNO || ' ' || MATERNO || ' ' || NOMBRE) EMPLEADO,
        LOWER(SUBSTR(NOMBRE, 1, 2) || '.' || PATERNO) NOM_USUARIO,
        LOWER(SUBSTR(ECIVIL,1,1)) || '*' || SUBSTR(RUTEMP,1,4) || 
          LOWER(SUBSTR(DIRECCION,1,1)) || '_' || UPPER(SUBSTR(DIRECCION,2,1)) AS CONTRASEÑA
FROM EMPLEADO;

--5
SELECT  NUMPROPIEDAD,
        IDTIPO AS TIPO,
        RENTA,
        NVL(GASTOCOMUN,0) AS "GASTO COMUN",
        RENTA * 1.062 AS "NUEVA RENTA",
        NVL(GASTOCOMUN * 1.062, 0) AS "GASTO COMUN REAJUSTADO"
FROM PROPIEDAD;
