--EJECUTAR COMO USUARIO SYSTEM
ALTER SYSTEM SET fixed_date='02/08/2017';

--1
SELECT  SUBSTR(RUTPROF, 1, LENGTH(RUTPROF)-1) || '-' || SUBSTR(RUTPROF,-1) AS RUN_PROFESIONAL,
        IDEMPRESA AS EMPRESA,
        TO_CHAR(HONORARIO, '$999G999G999') HONORARIO,
        TO_CHAR(INICIO, 'day DD-MM-YYYY') INICIO_ASESORIA,
        TO_CHAR(FIN, 'DD-MM-YYYY') TERMINO_ASESORIA
FROM ASESORIA
WHERE FIN = TO_DATE('30/07/2017','DD/MM/YYYY')
ORDER BY IDEMPRESA;

--2
SELECT  SUBSTR(RUTPROF, 1, LENGTH(RUTPROF)-1) || '-' || SUBSTR(RUTPROF,-1) AS RUN_PROFESIONAL,
        IDEMPRESA AS EMPRESA,
        TO_CHAR(HONORARIO, '$999G999G999') HONORARIO,
        TO_CHAR(INICIO, 'day DD-MM-YYYY') INICIO_ASESORIA,
        TO_CHAR(FIN, 'DD-MM-YYYY') TERMINO_ASESORIA
FROM ASESORIA
WHERE FIN = SYSDATE-1
--WHERE FIN = TO_DATE('02/08/2017','DD/MM/YYYY')-1
ORDER BY IDEMPRESA;

--3
SELECT  SUBSTR(RUTPROF, 1, LENGTH(RUTPROF)-1) || '-' || SUBSTR(RUTPROF,-1) AS RUN_PROFESIONAL,
        IDEMPRESA AS EMPRESA,
        TO_CHAR(HONORARIO, '$999G999G999') HONORARIO,
        TO_CHAR(INICIO, 'day DD-MM-YYYY') INICIO_ASESORIA,
        TO_CHAR(FIN, 'DD-Mon-YYYY') TERMINO_ASESORIA
FROM ASESORIA
WHERE TO_CHAR(FIN,'WW_YYYY') = TO_CHAR(SYSDATE,'WW_YYYY')
ORDER BY FIN;

--4
SELECT  SUBSTR(RUTPROF, 1, LENGTH(RUTPROF)-1) || '-' || SUBSTR(RUTPROF,-1) AS RUN_PROFESIONAL,
        IDEMPRESA AS EMPRESA,
        TO_CHAR(HONORARIO, '$999G999G999') HONORARIO,
        TO_CHAR(INICIO, 'day DD-MM-YYYY') INICIO_ASESORIA,
        TO_CHAR(FIN, 'DD-MM-YYYY') TERMINO_ASESORIA
FROM ASESORIA
WHERE TO_CHAR(FIN,'WW') = TO_CHAR(SYSDATE,'WW')-1 
      AND TO_CHAR(FIN,'YYYY') = TO_CHAR(SYSDATE,'YYYY')
ORDER BY FIN;

--5
SELECT  SUBSTR(RUTPROF, 1, LENGTH(RUTPROF)-1) || '-' || SUBSTR(RUTPROF,-1) AS RUN_PROFESIONAL,
        IDEMPRESA AS EMPRESA,
        TO_CHAR(HONORARIO, '$999G999G999') HONORARIO,
        TO_CHAR(INICIO, 'day DD-MM-YYYY') INICIO_ASESORIA,
        TO_CHAR(FIN, 'DD-MM-YYYY') TERMINO_ASESORIA
FROM ASESORIA
WHERE TO_CHAR(FIN,'WW') = TO_CHAR(SYSDATE,'WW')+1 
      AND TO_CHAR(FIN,'YYYY') = TO_CHAR(SYSDATE,'YYYY')
ORDER BY FIN;

--6
SELECT  SUBSTR(RUTPROF, 1, LENGTH(RUTPROF)-1) || '-' || SUBSTR(RUTPROF,-1) AS RUN_PROFESIONAL,
        IDEMPRESA AS EMPRESA,
        TO_CHAR(HONORARIO, '$999G999G999') HONORARIO,
        TO_CHAR(INICIO, 'day DD-Mon-YYYY') INICIO_ASESORIA,
        TO_CHAR(FIN, 'DD-MM-YYYY') TERMINO_ASESORIA
FROM ASESORIA
WHERE INICIO BETWEEN SYSDATE - 7 AND SYSDATE
ORDER BY INICIO;
