SELECT T.TITULO, A.NOMBRE||' '||A.APELLIDOS "NOMBRE"
FROM TITULO T JOIN AUTOR A
ON T.TITULOID = A.TITULOID;

SELECT E.DESCRIPCION "ESCUELA", COUNT (C.CARRERAID) "CARRERAS IMPARTIDAS"
FROM ESCUELA E JOIN CARRERA C
ON E.ESCUELAID = C.ESCUELAID
GROUP BY E.DESCRIPCION ORDER BY COUNT (C.CARRERAID) DESC;

